[package]
name = "server_http"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "26.0.1"
rust-ini = "0.21.3"
jsonwebtoken = "9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
